apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: proxy
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer

        # PUT YOUR FLOATING IP HERE:
        loadBalancerIP: "x.x.x.x"
        externalTrafficPolicy: Cluster
        annotations:
          # prevents errors when deleting clusters, leave as true
          loadbalancer.openstack.org/keep-floatingip: "true"

          # Set loadbalancing method: ROUND_ROBIN, LEAST_CONNECTIONS, SOURCE_IP, SOURCE_IP_PORT
          loadbalancer.openstack.org/lb-method: ROUND_ROBIN

          # Client inactivity timeout in milliseconds
          loadbalancer.openstack.org/timeout-client-data: "60000"

          # Set true to enable X-Forwarded-For Headers for HTTP
          loadbalancer.openstack.org/x-forwarded-for: "false"

          # Set to true to enable proxy protocol
          # see https://github.com/stfc/cloud-workshops/envoy-gateway/example-extras/proxy-protocol/README.md
          # loadbalancer.openstack.org/proxy-protocol: "true"
